module.exports = {
  purge: {
    content: [
      './src/**/*.html',
      './src/**/*.vue',
      './src/**/*.js',
      './src/**/*.svg',
    ],
  },
  prefix: '',
  important: false,
  separator: ':',
  theme: {
    extend: {
      colors: {
        light: {
          primary: 'rgba(255,255,255, 1)',
          secondary: 'rgba(255,255,255, .7)',
          hint: 'rgba(255,255,255, .5)',
          separator: 'rgba(255,255,255, .12)',
          shade: 'rgba(255,255,255, .06)',
        },
        dark: {
          primary: 'rgba(0,0,0,.87)',
          secondary: 'rgba(0,0,0,.54)',
          hint: 'rgba(0,0,0,.32)',
          separator: 'rgba(0,0,0,.12)',
          shade: 'rgba(0,0,0,.06)',
        },
      },
      inset: {
        '1/2': '50%',
        '1/3': '33.33333%',
        '1/4': '25%',
        '2/3': '66.66667%',
        '3/4': '75%',
        full: '100%',
        0: '0',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
      },
      maxWidth: {
        none: 'none',
      },
      maxHeight: {
        none: 'none',
      },
    },
    fontFamily: {
      sans: [
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        'ui-serif',
        'Georgia',
        'Cambria',
        '"Times New Roman"',
        'Times',
        'serif',
      ],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '4rem',
      '7xl': '5rem',
      '8xl': '6rem',
      '9xl': '7rem',
      '10xl': '8rem',
    },
    container: {
      center: true,
      padding: '2rem',
    },
  },
  variants: {},
  corePlugins: {},
  plugins: [],
}
